apiVersion: v1
kind: Secret
metadata:
  name: camunda-credentials
  namespace: ticketing
type: Opaque
stringData:
  zeebeClientCloudRegion: "<REGION>"
  zeebeClientCloudClusterId: "<CLUSTER_ID>"
  zeebeClientCloudClientId: "<CLIENT_ID>"
  zeebeClientCloudClientSecret: "<CLIENT_SECRET>"
  zeebeAddress: "<CLUSTER_ID>.<REGION>.zeebe.camunda.io:443"
  camundaOauthUrl: "https://login.cloud.camunda.io/oauth/token"
  zeebeAuthorizationServerUrl: "https://login.cloud.camunda.io/oauth/token"
