apiVersion: v1
kind: Secret
metadata:
  name: camunda-credentials
type: Opaque
stringData:
  zeebeClientCloudClusterId: "<CLUSTER_ID>"
  zeebeClientCloudClientId: "<CLIENT_ID>"
  zeebeClientCloudClientSecret: "<CLIENT_SECRET>"
  zeebeClientCloudRegion: "<REGION>"
  zeebeAddress: "<CLUSTER_ID>.<REGION>.zeebe.camunda.io:443"
