apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq/
  - booking-service/
  - payment-service/
  - seat-service/
  - ticket-service/

labels:
  - includeSelectors: false
    pairs:
      app: camunda-ticket-booking