apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rabbitmq-deployment.yaml
  - booking-deployment.yaml
  - booking-service.yaml
  - booking-hpa.yaml
  - seat-deployment.yaml
  - seat-service.yaml
  - payment-deployment.yaml
  - payment-service.yaml
  - ticket-deployment.yaml
  - ticket-service.yaml
