apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 409165006231.dkr.ecr.eu-west-3.amazonaws.com/payment-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 15
