apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat-service
  template:
    metadata:
      labels:
        app: seat-service
    spec:
      containers:
      - name: seat-service
        image: 937792903323.dkr.ecr.eu-west-3.amazonaws.com/seat-service:latest
        ports:
            - containerPort: 3001
        resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
        env:
        - name: PORT
          value: "3001"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: ZEEBE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: camunda-credentials
              key: zeebeClientCloudClientId
        - name: ZEEBE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: camunda-credentials
              key: zeebeClientCloudClientSecret
        - name: ZEEBE_ADDRESS
          valueFrom:
            secretKeyRef:
              name: camunda-credentials
              key: zeebeAddress
        - name: ZEEBE_AUTHORIZATION_SERVER_URL
          value: "https://login.cloud.camunda.io/oauth/token"