apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat-service
  template:
    metadata:
      labels:
        app: seat-service
    spec:
      containers:
      - name: seat-service
        image: 937792903323.dkr.ecr.eu-west-3.amazonaws.com/seat-service:latest
        ports:
            - containerPort: 3001
        resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
        env:
        - name: PORT
          value: "3001"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: ZEEBE_CLIENT_ID
          value: WSF9GRDRr.hs45KJ~Tp8M7N_.XC7KoAU
        - name: ZEEBE_CLIENT_SECRET
          value: "PkLQmENeEeQ~ogi_~spFTn86RmYxCzuHVPVlxCi4wj.Q1V0MBbiL0aTPOygbfoiU"
        - name: ZEEBE_ADDRESS
          value: "7bc2c2fe-3cf9-4950-9df3-86f75b0b64c4.cdg-1.zeebe.camunda.io:443"
        - name: ZEEBE_AUTHORIZATION_SERVER_URL
          value: "https://login.cloud.camunda.io/oauth/token"