apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: 937792903323.dkr.ecr.eu-west-3.amazonaws.com/booking-service:latest
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: ZEEBE_CLIENT_CLOUD_CLUSTERID
          value: 7bc2c2fe-3cf9-4950-9df3-86f75b0b64c4
        - name: ZEEBE_CLIENT_CLOUD_CLIENTID
          value: WSF9GRDRr.hs45KJ~Tp8M7N_.XC7KoAU
        - name: ZEEBE_CLIENT_CLOUD_CLIENTSECRET
          value: PkLQmENeEeQ~ogi_~spFTn86RmYxCzuHVPVlxCi4wj.Q1V0MBbiL0aTPOygbfoiU
        - name: ZEEBE_CLIENT_CLOUD_REGION
          value: cdg-1
        - name: TICKET_SERVICE_ENDPOINT
          value: "http://ticket-service:3003/ticket"