name: Build and Push

# Builds and pushes anytime code is pushed or merged to main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker Images
    runs-on: ubuntu-latest

    # Grab the code from repository and set up Java
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
        
        # Login to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
        
        # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

        # Build and push the booking service
      - name: Build and Push Java Booking Service
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd booking-service-java
          # Compile the fresh code first!
          mvn clean package -DskipTests
          # Build and push the image
          docker build -t $ECR_REGISTRY/booking-service:latest .
          docker push $ECR_REGISTRY/booking-service:latest
        
        # Build and push the node microservices
      - name: Build and Push Microservices
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd seat-service-nodejs
          docker build -t $ECR_REGISTRY/seat-service:latest .
          docker push $ECR_REGISTRY/seat-service:latest
          cd ..

          cd payment-service-nodejs
          docker build -t $ECR_REGISTRY/payment-service:latest .
          docker push $ECR_REGISTRY/payment-service:latest
          cd ..

          cd ticket-service-nodejs
          docker build -t $ECR_REGISTRY/ticket-service:latest .
          docker push $ECR_REGISTRY/ticket-service:latest


        # Update the new code changes by applying it on the kubernetes  
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region eu-west-3 \
            --name ticketing-cluster

      - name: Deploy Latest Images To EKS
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl -n $K8S_NAMESPACE set image deployment/booking-service booking-service=$ECR_REGISTRY/booking-service:$IMAGE_TAG       
          kubectl -n $K8S_NAMESPACE set image deployment/seat-service seat-service=$ECR_REGISTRY/seat-service:$IMAGE_TAG
          kubectl -n $K8S_NAMESPACE set image deployment/payment-service payment-service=$ECR_REGISTRY/payment-service:$IMAGE_TAG
          kubectl -n $K8S_NAMESPACE set image deployment/ticket-service ticket-service=$ECR_REGISTRY/ticket-service:$IMAGE_TAG

          kubectl -n $K8S_NAMESPACE rollout status deployment/booking-service --timeout=180s
          kubectl -n $K8S_NAMESPACE rollout status deployment/seat-service --timeout=180s
          kubectl -n $K8S_NAMESPACE rollout status deployment/payment-service --timeout=180s
          kubectl -n $K8S_NAMESPACE rollout status deployment/ticket-service --timeout=180s
