name: TEST

# Builds and pushes anytime code is pushed or merged to main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker Images
    runs-on: ubuntu-latest

    # Grab the code from repository and set up Java
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
        # Login to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
        
        # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
        # Update the new code changes by applying it on the kubernetes  
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region eu-west-3 \
            --name ticketing-cluster

      - name: Debug EKS auth
        run: |
          aws sts get-caller-identity
          kubectl config current-context
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/
